### ISSUE TITLE
Where to find zh_lib?

### ISSUE THREAD

**Issue by ghzhao88** [USTC-Video-Understanding/I3D_Finetune#3]
Can't find some functions used in test.py.  Please provide the code for the following modules.
from zh_lib.dataset import ActionDataset
from zh_lib.load_data import load_info
from zh_lib.feed_queue import FeedQueue
from zh_lib.label_trans import

**Comment by vra** [comment]
Hi @ghzhao88 ,
sorry for the inconvience, we are refactoring the project to make it more cleaner and easier to use. Once finished we will notice you.

**Comment by ghzhao88** [comment]
Thanks for your quick rely. Can you just send me the few files? I like to verify something.

**Comment by ghzhao88** [comment]
Another question, to my understanding, the flow.txt should include all files in trainlist01.txt, trainlist02.txt and trainlist03.txt and all files in testlist01.txt should not in flow.txt.  But v_YoYo_g01_c01.avi in both flow.txt and testlist01.txt.

**Comment by ghzhao88** [comment]
The zh_lib.zip you uploaded is empty. Please upload again.

**Comment by vra** [comment]
Sorry for the mistake, please [download](http://home.ustc.edu.cn/~wangyf11/zh_lib.zip) again.

**Comment by vra** [comment]
Hi @ghzhao88 ,
According to [this issue](https://github.com/USTC-Video-Understanding/I3D_Finetune/issues/2), the last fc layer should not use a non-linear layer. So we updated `test.py` and removed the `tf.nn.relu` parameter in the the last dense layer at [here](https://github.com/USTC-Video-Understanding/I3D_Finetune/blob/master/test.py#L101) and [here](https://github.com/USTC-Video-Understanding/I3D_Finetune/blob/master/test.py#L111), while the uploaded models were generated using previous version of code. Thus an easy way to verify the pre-trained moedels is adding `tf.nn.relu` to the above mentioned two lines, like this:
```python
            rgb_fc_out = tf.layers.dense(
                rgb_logits_dropout, _CLASS_NUM[dataset], tf.nn.relu, use_bias=True)
            flow_fc_out = tf.layers.dense(
                flow_logits_dropout, _CLASS_NUM[dataset], tf.nn.relu, use_bias=True)
```

**Comment by ghzhao88** [comment]
I added tf.nn.relu in test.py but the mixed result is still the same running testlist01.txt. 

test accuracy: 0.6088

**Comment by ghzhao88** [comment]
I have another issue. I tried to train ucf101 rgb data from scratch but failed, here is the log, anything wrong?

/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #2
  (fname, cnt))
/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #3
  (fname, cnt))
2018-06-18 03:12:30.670340: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-18 03:12:30.756955: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-06-18 03:12:30.757378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:1e.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-06-18 03:12:30.757408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-18 03:12:31.039003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-18 03:12:31.039058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0
2018-06-18 03:12:31.039067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N
2018-06-18 03:12:31.039382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10763 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
INFO:tensorflow:Restoring parameters from ./data/checkpoints/rgb_imagenet/model.ckpt
2018-06-18 03:12:38.140469: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./data/checkpoints/rgb_imagenet/model.ckpt: Data loss: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?
2018-06-18 03:12:38.141044: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./data/checkpoints/rgb_imagenet/model.ckpt: Data loss: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?
2018-06-18 03:12:38.141078: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_tensor.cc:170 : Data loss: Unable to open table file ./data/checkpoints/rgb_imagenet/model.ckpt: Data loss: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "finetune.py", line 289, in <module>
    main(**vars(p.parse_args()))
  File "finetune.py", line 211, in main
    saver.restore(sess, _CHECKPOINT_PATHS[train_data.mode+'_imagenet'])
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1802, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./data/checkpoints/rgb_imagenet/model.ckpt: Data loss: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
         [[Node: save/RestoreV2/_397 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_397_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op u'save/RestoreV2', defined at:
  File "finetune.py", line 289, in <module>
    main(**vars(p.parse_args()))
  File "finetune.py", line 183, in main
    saver = tf.train.Saver(var_list=variable_map, reshape=True)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1338, in __init__
    self.build()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 835, in _build_internal
    restore_sequentially, reshape)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 472, in _AddRestoreOps
    restore_sequentially)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 886, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

DataLossError (see above for traceback): Unable to open table file ./data/checkpoints/rgb_imagenet/model.ckpt: Data loss: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
         [[Node: save/RestoreV2/_397 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_397_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

ubuntu@ip-172-31-39-205:~/hmr/harryz/new/I3D_Finetune$
ubuntu@ip-172-31-39-205:~/hmr/harryz/new/I3D_Finetune$
ubuntu@ip-172-31-39-205:~/hmr/harryz/new/I3D_Finetune$
ubuntu@ip-172-31-39-205:~/hmr/harryz/new/I3D_Finetune$
ubuntu@ip-172-31-39-205:~/hmr/harryz/new/I3D_Finetune$
ubuntu@ip-172-31-39-205:~/hmr/harryz/new/I3D_Finetune$ vi rgb.log
ubuntu@ip-172-31-39-205:~/hmr/harryz/new/I3D_Finetune$ vi rgb.log
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./data/checkpoints/rgb_imagenet/model.ckpt: Data loss: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
         [[Node: save/RestoreV2/_397 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_397_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op u'save/RestoreV2', defined at:
  File "finetune.py", line 289, in <module>
    main(**vars(p.parse_args()))
  File "finetune.py", line 183, in main
    saver = tf.train.Saver(var_list=variable_map, reshape=True)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1338, in __init__
    self.build()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 835, in _build_internal
    restore_sequentially, reshape)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 472, in _AddRestoreOps
    restore_sequentially)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 886, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

DataLossError (see above for traceback): Unable to open table file ./data/checkpoints/rgb_imagenet/model.ckpt: Data loss: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
         [[Node: save/RestoreV2/_397 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_397_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by ghzhao88** [comment]
If I  remove the following line in finetune.py , then I got another kind of error.
#saver.restore(sess, _CHECKPOINT_PATHS[train_data.mode+'_imagenet'])

Traceback (most recent call last):
  File "finetune.py", line 289, in <module>
    main(**vars(p.parse_args()))
  File "finetune.py", line 228, in main
    feed_dict={dropout_holder: _DROPOUT, is_train_holder: True})
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot batch tensors with different shapes in component 0. First element had shape [1,64,224,224,2] and element 5 had shape [1,52,224,224,2].
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>], output_types=[DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
         [[Node: IteratorGetNext/_51 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_308_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op u'IteratorGetNext', defined at:
  File "finetune.py", line 289, in <module>
    main(**vars(p.parse_args()))
  File "finetune.py", line 139, in main
    clip_holder, label_holder = iterator.get_next()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 370, in get_next
    name=name)), self._output_types,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1466, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot batch tensors with different shapes in component 0. First element had shape [1,64,224,224,2] and element 5 had shape [1,52,224,224,2].
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>], output_types=[DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
         [[Node: IteratorGetNext/_51 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_308_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by ghzhao88** [comment]
I got another error when use ucf101 data to train from scratch:

Traceback (most recent call last):
  File "finetune.py", line 289, in <module>
    main(**vars(p.parse_args()))
  File "finetune.py", line 228, in main
    feed_dict={dropout_holder: _DROPOUT, is_train_holder: True})
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot batch tensors with different shapes in component 0. First element had shape [1,63,224,224,3] and element 1 had shape [1,64,224,224,3].
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>], output_types=[DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

Caused by op u'IteratorGetNext', defined at:
  File "finetune.py", line 289, in <module>
    main(**vars(p.parse_args()))
  File "finetune.py", line 139, in main
    clip_holder, label_holder = iterator.get_next()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 370, in get_next
    name=name)), self._output_types,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1466, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot batch tensors with different shapes in component 0. First element had shape [1,63,224,224,3] and element 1 had shape [1,64,224,224,3].
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>], output_types=[DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

**Comment by panna19951227** [comment]
@ghzhao88 I have met the same problem,Have you addressed it?

**Comment by ghzhao88** [comment]
Not fixed yet.

**Comment by ghzhao88** [comment]
I have another issue. I tried to train the model using another set of data and got accuracy 0.65 but the checkpoint is not saved.  /data/checkpoints/flow_scratch/model.ckpt.meta is still the same after training. I tried to set the following two constants but still the same. Any thing wrong?
_RUN_TEST_THRESH = 0.5
# If the accuracy on testing data higher than this value, save the model
_SAVE_MODEL_THRESH = 0.5

**Comment by MrCuiHao** [comment]
@ghzhao88  你好，请问你解决这个混合预测问题了吗？我现在仅仅是测试了rgb流，Top-1错误率比较正常
