### ISSUE TITLE
An error when running finetune.py 

### ISSUE THREAD

**Issue by liuxuepdf** [USTC-Video-Understanding/I3D_Finetune#6]
When I run the finetune.py an error ocurred. Below is the info:

Traceback (most recent call last):
  File "finetune.py", line 305, in <module>
    main(**vars(p.parse_args()))
  File "finetune.py", line 237, in main
    feed_dict={dropout_holder: _DROPOUT, is_train_holder: True})
  File "/home/liuxuepdf/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/liuxuepdf/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/liuxuepdf/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/liuxuepdf/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: TypeError: 'NoneType' object is not iterable
	 [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_STRING, DT_STRING], Tout=[DT_FLOAT, DT_INT64], token="pyfunc_0"](arg0, PyFunc/input_1, PyFunc/input_2)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>], output_types=[DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
 
Could you please tell me how to solve this error? Thx

**Comment by BigBugGrow** [comment]
I have encountered the same problem, have you solved it?

**Comment by Easyfeng222** [comment]
@liuxuepdf @BigBugGrow I have encountered the same problem, have you solved it?
